---
- name: Install jenkins helm chart
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: jenkins
      version: "{{ jenkins_chart_version }}"
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    values: "{{ jenkins_chart_values }}"
    state: present
    name: "{{ jenkins_release_name }}"
    namespace: "{{ jenkins_namespace }}"
