---
# configue tiller connectivity if required
- include: tiller.yml
  when: l_helm_host is not defined or l_helm_port is not defined

# install jenkins
- include: jenkins.yml

# setup ldap
- include: ldap.yml
